### ISSUE TITLE
Building the package (react) fails locally (with Yarn)

### ISSUE THREAD

**Issue by mindreframer** [oscarpas/panache#15]
**Describe the bug**
```
$ git clone https://github.com/oscarpas/panache/
$ git log -n 1
commit 5262974a4e6891b569848d8145bd280c3326b5e9 (HEAD -> main, origin/main, origin/HEAD)
Author: oscarpas <pastarus@gmail.com>
Date:   Tue Mar 16 18:39:33 2021 +0100

    Update README.md

$ cd panache && yarn 
$ cd packages/react
$ yarn build 

yarn build
yarn run v1.22.10
$ rollup -c

src/main.ts → dist/panache.cjs.js, dist/panache.esm.js...
(!) Plugin typescript: @rollup/plugin-typescript TS6133: 'ResponsiveVariable' is declared but its value is never read.

1 import type { ResponsiveVariable } from '../types'
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

(!) Plugin typescript: @rollup/plugin-typescript TS2792: Cannot find module 'panache-core/dist/types'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?

2 import type { Styles, StyleGenerator, StyleObject, StyleList } from 'panache-core/dist/types'
                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~

(!) Plugin typescript: @rollup/plugin-typescript TS2792: Cannot find module 'panache-core'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?

4 import { hash, mergeObjects } from 'panache-core'
                                     ~~~~~~~~~~~~~~


3 import { Sheet } from 'panache-core'
                        ~~~~~~~~~~~~~~

(!) Plugin typescript: @rollup/plugin-typescript TS2349: This expression is not callable.
  Type 'never' has no call signatures.

44     : isStyleGenerator(styles) ? styles(props) : styles
                                    ~~~~~~

(!) Plugin typescript: @rollup/plugin-typescript TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'ReactNode'.
      Type 'unknown' is not assignable to type 'ReactPortal'.

15       css,
         ~~~

  ../../node_modules/@types/react/index.d.ts:296:14
    296     function createElement<P extends {}>(
                     ~~~~~~~~~~~~~
    The last overload is declared here.

[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src/factory/factory.ts (2:12)
1: import * as React from 'react'
2: import type { Styles, StyleGenerator, StyleObject, StyleList } from 'panache-core/dist/types'
               ^
3: // eslint-disable-next-line
4: import { hash, mergeObjects } from 'panache-core'
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/Users/roman/Desktop/work/qwzrd/qwzrd-ui/node_modules/panache-react/panache/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at Module.error (/Users/roman/Desktop/work/qwzrd/qwzrd-ui/node_modules/panache-react/panache/node_modules/rollup/dist/shared/node-entry.js:9824:16)
    at tryParse (/Users/roman/Desktop/work/qwzrd/qwzrd-ui/node_modules/panache-react/panache/node_modules/rollup/dist/shared/node-entry.js:9717:23)
    at Module.setSource (/Users/roman/Desktop/work/qwzrd/qwzrd-ui/node_modules/panache-react/panache/node_modules/rollup/dist/shared/node-entry.js:10080:33)
    at /Users/roman/Desktop/work/qwzrd/qwzrd-ui/node_modules/panache-react/panache/node_modules/rollup/dist/shared/node-entry.js:12366:20
    at async Promise.all (index 1)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)

error Command failed with exit code 1.
```

**Additional context**
```
$ yarn version
yarn version v1.22.10
info Current version: 0.2.0
```

**Comment by oscarpas** [comment]
The react package depends on the core package, so that needs to be built first. I've added some basic documentation [here](https://github.com/oscarpas/panache/tree/main/packages/react#readme), I'll expand on that in the future.
